---
resources:
- name: hello-resource
  type: git
  source: 
  - uri: https://github.com/uknadkarni/c1/hw.yml

jobs:
- name: hello-world
  plan: 
  - get: hello-resource
  - task: say-hello
    file: tasks/hw.yml

