---
resources:
- name: hello-resource
  type: git
  source: 
  - uri: git@github.com:uknadkarni/c1.git

jobs:
- name: hello-world
  plan: 
  - get: hello-resource
  - task: say-hello
    file: tasks/hello-world/hw.yml

